### PR TITLE
PCRM-3979 Implement Lambda update

### PR DESCRIPTION
**Pull request by aparimoo-nhs**
Removed the missing additional logging file fix

### CODE REVIEW

**Review by jamesnunnnhs — COMMENTED** [review]
Do we now need to supply any sort of config that defines any custom log message properties now we don't have cloudlogbase.cfg?

**Comment by aparimoo-nhs** [comment]
> Do we now need to supply any sort of config that defines any custom log message properties now we don't have cloudlogbase.cfg?

We don't have our custom log file as yet. For now we using the default cloudlogbase.cfg. Could be done as a part of another story.

**Review by jamesnunnnhs — COMMENTED** [review]
Does this update remove the need to define the `initialise` function too? If so, is it worth doing now?

**Review by josh-scargill-nhsd — APPROVED** [review]

**Comment by joeds13** [comment]
Updating LR-25 Post Office Lambda not included in this PR

**Comment by aparimoo-nhs** [comment]
> Does this update remove the need to define the `initialise` function too? If so, is it worth doing now?

No, there is no change in terms of `initialise`  also I think @abbas-khan8  is using `initialise ` for the logger now isn't?

**Review by HarveyNHS — APPROVED** [review]
Approved

**Review by jamesnunnnhs — APPROVED** [review]

**Pull request merged**
